In [4]:
import numpy as np
import random

In [5]:
state = np.zeros(9)
print(state)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [60]:
NUM_EPISODES = 10

class Environment:
    '''三目並べを実行する環境のクラス'''
    
    def __init__(self):
        self.game_board = np.zeros(9)
        self.winner = ""
    
    def run(self):
        
        complete_episodes = 0
        
        for episode in range(NUM_EPISODES):
            self.game_board = np.zeros(9)
            self.winner = ""
            
            for step in range(9):
                self.random_player_turn1()
                print("先手")
                game_board = np.reshape(self.game_board, [3,3])
                print(game_board)
                if(self.winner != ""):
                    complete_episodes += 1
                    print(self.winner, "の勝ち")
                    break

                self.random_player_turn2()
                print("後手")
                game_board = np.reshape(self.game_board, [3,3])
                print(game_board)
                if(self.winner != ""):
                    complete_episodes = 0
                    print(self.winner, "の勝ち")
                    break

                if step == 8:
                    complete_episodes = 0
                    print("引き分け")
                    break
                    
            if (complete_episodes == 2):
                print(self.winner, "の2連勝")
                break
        
    def q_learning_turn(self):
        pos = self.agent.get_action()
        self.state[i] = 1
        is_win = self.is_win_func()
        if (is_win):
            self.winner = "Q学習"
        
    def random_player_turn1(self):
        while(True):
            i = random.randint(0,8)
            if self.game_board[i] == 0:
                self.game_board[i] = 1
                break
        is_win = self.is_win_func()
        if (is_win):
            self.winner = "ランダムプレイヤー1"
        
    def random_player_turn2(self):
        while(True):
            i = random.randint(0,8)
            if self.game_board[i] == 0:
                self.game_board[i] =2
                break
        is_win = self.is_win_func()
        if (is_win):
            self.winner = "ランダムプレイヤー2"
        
    def is_win_func(self):
        # 勝ち手を列挙
        lines = [
          [0, 1, 2],
          [3, 4, 5],
          [6, 7, 8],
          [0, 3, 6],
          [1, 4, 7],
          [2, 5, 8],
          [0, 4, 8],
          [2, 4, 6],
        ]
        for i in range(0, len(lines)):
            [a, b, c] = lines[i]
            
            if self.game_board[a] and self.game_board[a] == self.game_board[b] and self.game_board[a] == self.game_board[c]: 
                return True
        return False

In [61]:
tic_tac_toe_env = Environment()
tic_tac_toe_env.run()

先手
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
後手
[[0. 1. 0.]
 [0. 0. 0.]
 [2. 0. 0.]]
先手
[[0. 1. 0.]
 [0. 0. 0.]
 [2. 1. 0.]]
後手
[[0. 1. 2.]
 [0. 0. 0.]
 [2. 1. 0.]]
先手
[[0. 1. 2.]
 [0. 0. 0.]
 [2. 1. 1.]]
後手
[[2. 1. 2.]
 [0. 0. 0.]
 [2. 1. 1.]]
先手
[[2. 1. 2.]
 [0. 1. 0.]
 [2. 1. 1.]]
ランダムプレイヤー1 の勝ち
先手
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
後手
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
先手
[[0. 0. 0.]
 [0. 1. 2.]
 [1. 0. 0.]]
後手
[[0. 0. 0.]
 [2. 1. 2.]
 [1. 0. 0.]]
先手
[[0. 0. 0.]
 [2. 1. 2.]
 [1. 1. 0.]]
後手
[[0. 0. 2.]
 [2. 1. 2.]
 [1. 1. 0.]]
先手
[[0. 1. 2.]
 [2. 1. 2.]
 [1. 1. 0.]]
ランダムプレイヤー1 の勝ち
ランダムプレイヤー1 の2連勝
